<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Version>1.1.0</Version>
        <AssemblyVersion>1.1.0</AssemblyVersion>
        <FileVersion>1.1.0</FileVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
        <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.8" />
        <PackageReference Include="PKHeX.Core" Version="25.12.21" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.3" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
    </ItemGroup>
    <ItemGroup>
        <Compile Remove="BeastVault.Api.Tests\**\*.cs" />
        <Content Remove="BeastVault.Api.Tests\**\*" />
        <None Remove="BeastVault.Api.Tests\**\*" />
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Data\SavePokedexCatalog.json" />
    </ItemGroup>
</Project>
