// <auto-generated />
using System;
using BeastVault.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeastVault.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527160000_AddSpriteDataBlobs")]
    partial class AddSpriteDataBlobs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.PokedexPokemon", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abilities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ArtworkData")
                        .HasColumnType("BLOB");

                    b.Property<string>("ArtworkLocalPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("BaseExperience")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseStats")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cries")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameIndices")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MovesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ShinyData")
                        .HasColumnType("BLOB");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SpriteData")
                        .HasColumnType("BLOB");

                    b.Property<string>("SpriteLocalPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sprites")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Types")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("PokemonId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("PokedexPokemon");
                });
#pragma warning restore 612, 618
        }
    }
}
