// <auto-generated />
using System;
using BeastVault.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeastVault.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260801155311_AddTcgCollection")]
    partial class AddTcgCollection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.BulbapediaCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntriesCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameMeaning")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NormalizedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedError")
                        .HasColumnType("TEXT");

                    b.Property<int>("NormalizedStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PageTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParsedSections")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawHtml")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpritesCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("BulbapediaCache");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.CachedImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DownloadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SpeciesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceUrl")
                        .IsUnique();

                    b.HasIndex("SpeciesId");

                    b.ToTable("CachedImages");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.FileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RawBlob")
                        .HasColumnType("BLOB");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Sha256")
                        .IsUnique();

                    b.ToTable("Files");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.FileTagEntity", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FileId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("FileTags");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.HouseholdAccessToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("ConnectionId", "FamilyId");

                    b.ToTable("HouseholdAccessTokens");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.HouseholdAuthorizationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeChallenge")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.HasIndex("ConnectionId");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("HouseholdAuthorizationCodes");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.HouseholdConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrantedScopes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ClientId");

                    b.ToTable("HouseholdConnections");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.HouseholdRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("ReplacedByTokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("ConnectionId", "FamilyId");

                    b.ToTable("HouseholdRefreshTokens");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.MoveEntity", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentPp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoveId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PpUps")
                        .HasColumnType("INTEGER");

                    b.HasKey("PokemonId", "Slot");

                    b.ToTable("Moves");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.PokedexAbility", b =>
                {
                    b.Property<int>("AbilityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMainSeries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortEffect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AbilityId");

                    b.ToTable("PokedexAbilities");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.PokedexEntry", b =>
                {
                    b.Property<int>("SpeciesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseHappiness")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CaptureRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EggGroups")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EvolutionChainId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvolutionChainUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("FormsSwitchable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenderRate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrowthRate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Habitat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasGenderDifferences")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HatchCounter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBaby")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLegendary")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMythical")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalizedNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Varieties")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SpeciesId");

                    b.ToTable("PokedexEntries");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.PokedexEvolutionChain", b =>
                {
                    b.Property<int>("ChainId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChainJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChainId");

                    b.ToTable("PokedexEvolutionChains");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.PokedexFlavorEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId", "Language", "GameVersion");

                    b.ToTable("PokedexFlavorEntries");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.PokedexItem", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FlingPower")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpriteLocalPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpriteUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("Category");

                    b.ToTable("PokedexItems");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.PokedexLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Game")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId", "Game");

                    b.ToTable("PokedexLocations");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.PokedexMove", b =>
                {
                    b.Property<int>("MoveId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Accuracy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DamageClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PP")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MoveId");

                    b.HasIndex("Type");

                    b.ToTable("PokedexMoves");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.PokedexPokemon", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abilities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ArtworkData")
                        .HasColumnType("BLOB");

                    b.Property<string>("ArtworkLocalPath")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ArtworkShinyData")
                        .HasColumnType("BLOB");

                    b.Property<int>("BaseExperience")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseStats")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cries")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameIndices")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("GithubShinySpriteData")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("GithubSpriteData")
                        .HasColumnType("BLOB");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("HomeShinyData")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("HomeSpriteData")
                        .HasColumnType("BLOB");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MovesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ShinyData")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ShowdownData")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ShowdownShinyData")
                        .HasColumnType("BLOB");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SpriteData")
                        .HasColumnType("BLOB");

                    b.Property<string>("SpriteLocalPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sprites")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Types")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("PokemonId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("PokedexPokemon");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.PokedexSpriteEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackLocalPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackShinyLocalPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameSlug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalLocalPath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShinyLocalPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.HasIndex("SpeciesId", "GameSlug");

                    b.ToTable("PokedexSpriteEntries");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.PokedexType", b =>
                {
                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DamageRelations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TypeId");

                    b.ToTable("PokedexTypes");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.PokemonBoxEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SortOrder");

                    b.ToTable("PokemonBoxes");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.PokemonBoxSlotEntity", b =>
                {
                    b.Property<int>("BoxId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("BoxId", "SlotIndex");

                    b.HasIndex("PokemonId")
                        .IsUnique();

                    b.ToTable("PokemonBoxSlots");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.PokemonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbilityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BallId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanGigantamax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContestBeauty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContestCool")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContestCute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContestSheen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContestSmart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContestTough")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentFriendship")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentHandler")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DynamaxLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EggLocation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EggMetDate")
                        .HasColumnType("TEXT");

                    b.Property<uint>("EncryptionConstant")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FatefulEncounter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Favorite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Form")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("FormArgument")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HandlingTrainerFriendship")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HandlingTrainerGender")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HandlingTrainerLanguage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HandlingTrainerMemory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HandlingTrainerMemoryFeeling")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HandlingTrainerMemoryIntensity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HandlingTrainerMemoryVariable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HandlingTrainerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HeightScalar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeldItemId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEgg")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsShiny")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MetDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MetLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetLocation")
                        .HasColumnType("TEXT");

                    b.Property<int>("Nature")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("OTGender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OTLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OriginGame")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OriginalTrainerMemory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OriginalTrainerMemoryFeeling")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OriginalTrainerMemoryIntensity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OriginalTrainerMemoryVariable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OtName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("PersonalityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PokerusDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PokerusState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PokerusStrain")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Scale")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpriteKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeraType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeightScalar")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("OriginGame");

                    b.HasIndex("UserId");

                    b.HasIndex("SpeciesId", "IsShiny");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.PokemonTagEntity", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("PokemonId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PokemonTags");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.RelearnMoveEntity", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoveId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PokemonId", "Slot");

                    b.ToTable("RelearnMoves");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.SaveFileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChecksumsValid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("OriginGame")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RawBlob")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("SaveType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ImportedAt");

                    b.HasIndex("UserId", "Sha256")
                        .IsUnique();

                    b.ToTable("SaveFiles");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.SavePokedexEntryEntity", b =>
                {
                    b.Property<int>("SaveFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Caught")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Seen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SaveFileId", "SpeciesId");

                    b.ToTable("SavePokedexEntries");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.SavePokemonPreviewEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AbilityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BoxIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Form")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeldItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEgg")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsShiny")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Location")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MovesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Nature")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NatureName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT");

                    b.Property<string>("PokemonHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PokemonStoredHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SaveFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PokemonHash");

                    b.HasIndex("SaveFileId", "Location", "BoxIndex", "SlotIndex")
                        .IsUnique();

                    b.ToTable("SavePokemonPreviews");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.SaveTrainerEntity", b =>
                {
                    b.Property<int>("SaveFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BadgeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DexCaught")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DexSeen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("Money")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayTimeHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("SecretId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("TrainerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrainerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SaveFileId");

                    b.ToTable("SaveTrainers");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.StatsEntity", b =>
                {
                    b.Property<int>("PokemonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EvAtk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EvDef")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EvHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EvSpa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EvSpd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EvSpe")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HyperTrainedAtk")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HyperTrainedDef")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HyperTrainedHp")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HyperTrainedSpa")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HyperTrainedSpd")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HyperTrainedSpe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IvAtk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IvDef")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IvHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IvSpa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IvSpd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IvSpe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatAtk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatDef")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatHpCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatSpa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatSpd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatSpe")
                        .HasColumnType("INTEGER");

                    b.HasKey("PokemonId");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.TagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.TcgCardEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardmarketUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DetailedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageLarge")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageSmall")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalPokedexNumbersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PokemonTcgIoId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceEur")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PriceUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceUsd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderCardId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .HasColumnType("TEXT");

                    b.Property<int>("SetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TcgplayerUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("VariantPricesEurJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VariantPricesUsdJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VariantsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Provider", "ProviderCardId")
                        .IsUnique();

                    b.HasIndex("SetId", "Number");

                    b.ToTable("TcgCards");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.TcgSetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CardsSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameEn")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrintedTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderSetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Series")
                        .HasColumnType("TEXT");

                    b.Property<string>("SymbolUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseDate");

                    b.HasIndex("Provider", "ProviderSetId")
                        .IsUnique();

                    b.ToTable("TcgSets");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.UserApiCredentialEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFour")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "Provider");

                    b.ToTable("UserApiCredentials");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.UserPreference", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrowseLayout")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KanbanDragMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizeDensity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpriteType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ViewMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.UserTcgCardEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("UserId", "AddedAt");

                    b.HasIndex("UserId", "CardId", "Variant", "Condition", "Language")
                        .IsUnique();

                    b.ToTable("UserTcgCards");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.FileEntity", b =>
                {
                    b.HasOne("BeastVault.Api.Domain.Entities.User", "User")
                        .WithMany("Files")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.FileTagEntity", b =>
                {
                    b.HasOne("BeastVault.Api.Domain.Entities.FileEntity", "File")
                        .WithMany("FileTags")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeastVault.Api.Domain.Entities.TagEntity", "Tag")
                        .WithMany("FileTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.HouseholdAccessToken", b =>
                {
                    b.HasOne("BeastVault.Api.Domain.Entities.HouseholdConnection", "Connection")
                        .WithMany("AccessTokens")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.HouseholdAuthorizationCode", b =>
                {
                    b.HasOne("BeastVault.Api.Domain.Entities.HouseholdConnection", "Connection")
                        .WithMany("AuthorizationCodes")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.HouseholdConnection", b =>
                {
                    b.HasOne("BeastVault.Api.Domain.Entities.User", "User")
                        .WithMany("HouseholdConnections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.HouseholdRefreshToken", b =>
                {
                    b.HasOne("BeastVault.Api.Domain.Entities.HouseholdConnection", "Connection")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeastVault.Api.Domain.Entities.HouseholdRefreshToken", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Connection");

                    b.Navigation("ReplacedByToken");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.MoveEntity", b =>
                {
                    b.HasOne("BeastVault.Api.Domain.Entities.PokemonEntity", null)
                        .WithMany("Moves")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.PokemonBoxEntity", b =>
                {
                    b.HasOne("BeastVault.Api.Domain.Entities.User", "User")
                        .WithMany("PokemonBoxes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.PokemonBoxSlotEntity", b =>
                {
                    b.HasOne("BeastVault.Api.Domain.Entities.PokemonBoxEntity", "Box")
                        .WithMany("Slots")
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeastVault.Api.Domain.Entities.PokemonEntity", "Pokemon")
                        .WithOne("BoxSlot")
                        .HasForeignKey("BeastVault.Api.Domain.Entities.PokemonBoxSlotEntity", "PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Box");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.PokemonEntity", b =>
                {
                    b.HasOne("BeastVault.Api.Domain.Entities.FileEntity", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeastVault.Api.Domain.Entities.User", "User")
                        .WithMany("Pokemon")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.PokemonTagEntity", b =>
                {
                    b.HasOne("BeastVault.Api.Domain.Entities.PokemonEntity", "Pokemon")
                        .WithMany("PokemonTags")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeastVault.Api.Domain.Entities.TagEntity", "Tag")
                        .WithMany("PokemonTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.RelearnMoveEntity", b =>
                {
                    b.HasOne("BeastVault.Api.Domain.Entities.PokemonEntity", null)
                        .WithMany("RelearnMoves")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.SaveFileEntity", b =>
                {
                    b.HasOne("BeastVault.Api.Domain.Entities.User", "User")
                        .WithMany("SaveFiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.SavePokedexEntryEntity", b =>
                {
                    b.HasOne("BeastVault.Api.Domain.Entities.SaveFileEntity", "SaveFile")
                        .WithMany("PokedexEntries")
                        .HasForeignKey("SaveFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaveFile");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.SavePokemonPreviewEntity", b =>
                {
                    b.HasOne("BeastVault.Api.Domain.Entities.SaveFileEntity", "SaveFile")
                        .WithMany("PokemonPreviews")
                        .HasForeignKey("SaveFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaveFile");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.SaveTrainerEntity", b =>
                {
                    b.HasOne("BeastVault.Api.Domain.Entities.SaveFileEntity", "SaveFile")
                        .WithOne("Trainer")
                        .HasForeignKey("BeastVault.Api.Domain.Entities.SaveTrainerEntity", "SaveFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaveFile");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.TagEntity", b =>
                {
                    b.HasOne("BeastVault.Api.Domain.Entities.User", "User")
                        .WithMany("Tags")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.TcgCardEntity", b =>
                {
                    b.HasOne("BeastVault.Api.Domain.Entities.TcgSetEntity", "Set")
                        .WithMany("Cards")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.UserApiCredentialEntity", b =>
                {
                    b.HasOne("BeastVault.Api.Domain.Entities.User", "User")
                        .WithMany("ApiCredentials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.UserPreference", b =>
                {
                    b.HasOne("BeastVault.Api.Domain.Entities.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("BeastVault.Api.Domain.Entities.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.UserTcgCardEntity", b =>
                {
                    b.HasOne("BeastVault.Api.Domain.Entities.TcgCardEntity", "Card")
                        .WithMany("OwnedEntries")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeastVault.Api.Domain.Entities.User", "User")
                        .WithMany("TcgCards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.FileEntity", b =>
                {
                    b.Navigation("FileTags");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.HouseholdConnection", b =>
                {
                    b.Navigation("AccessTokens");

                    b.Navigation("AuthorizationCodes");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.PokemonBoxEntity", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.PokemonEntity", b =>
                {
                    b.Navigation("BoxSlot");

                    b.Navigation("Moves");

                    b.Navigation("PokemonTags");

                    b.Navigation("RelearnMoves");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.SaveFileEntity", b =>
                {
                    b.Navigation("PokedexEntries");

                    b.Navigation("PokemonPreviews");

                    b.Navigation("Trainer")
                        .IsRequired();
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.TagEntity", b =>
                {
                    b.Navigation("FileTags");

                    b.Navigation("PokemonTags");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.TcgCardEntity", b =>
                {
                    b.Navigation("OwnedEntries");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.TcgSetEntity", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("BeastVault.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("ApiCredentials");

                    b.Navigation("Files");

                    b.Navigation("HouseholdConnections");

                    b.Navigation("Pokemon");

                    b.Navigation("PokemonBoxes");

                    b.Navigation("Preferences");

                    b.Navigation("SaveFiles");

                    b.Navigation("Tags");

                    b.Navigation("TcgCards");
                });
#pragma warning restore 612, 618
        }
    }
}
